### PR TITLE
Enabling cache and weaving

### PR DESCRIPTION
**Pull request by CiGit**
JPA lvl 2 cache
Eclipselink weaving

### CODE REVIEW

**Comment by CiGit** [comment]
MessageFacadeTest#testInboxSendTrigger Currently fails __sometimes__ :fearful: on my system.
Windows 10, java 1.8.0_74

**Comment by maxencelaurent** [comment]
see ResourceFacadeTest's  testRemoveAssignment and testRemoveAssignmentFromScript.

Both assigns then unassigns a resource to a task. First one by directly using resourceFacade, second one by using the facade witin such a JS script (scriptFacade.eval).

Second one always fails : utter nonsense

**Comment by CiGit** [comment]
`MessageFacadeTest#testInboxSendTrigger` also failed on travis __sometimes__ (1/2)... 
~~system dependant~~

**Comment by CiGit** [comment]
Disabling weaving seems to "fix" `MessageFacadeTest#testInboxSendTrigger`

**Pull request merged**
